name: CI-iOS




# Controls when the action will run. Triggers the workflow on push or pull request

# events but only for the master branch

on: [push, pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build-and-run:

    # The type of runner that the job will run on

    runs-on: macos-latest




    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - uses: actions/checkout@v2




    - name: Select Xcode

      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app

      

    - name: Xcode version

      run: /usr/bin/xcodebuild -version

      
    - name: Install cocoapods dependencies
    
      working-directory: ./Messenger
      run: pod install
      
      
    - name: Build

      run: xcodebuild clean build -workspace Messenger/Messenger.xcworkspace -scheme "Messenger" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=YES
